// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekfcmldoxlzdqjgpemvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZmNtbGRveGx6ZHFqZ3BlbXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzIyNzAsImV4cCI6MjA2NDgwODI3MH0.ksrdOwHtjCX0GcreFOXn-TDAiZFtb6IR6yRAzLXiDv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);